package com.lambda.kotlinroomahpokedex

import com.lambda.kotlinroomahpokedex.models.Pokemon

object PokemonMockData{
    var pokemonList = mutableListOf<Pokemon>()

    init{
        pokemonList.add(
            Pokemon(
                1,
                "bulbasaur",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
            )
        )
        pokemonList.add(
            Pokemon(
                2,
                "ivysaur",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png"
            )
        )
        pokemonList.add(
            Pokemon(
                3,
                "venusaur",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png"
            )
        )
        pokemonList.add(
            Pokemon(
                4,
                "charmander",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png"
            )
        )
        pokemonList.add(
            Pokemon(
                5,
                "charmeleon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png"
            )
        )
        pokemonList.add(
            Pokemon(
                6,
                "charizard",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png"
            )
        )
        pokemonList.add(
            Pokemon(
                7,
                "squirtle",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png"
            )
        )
        pokemonList.add(
            Pokemon(
                8,
                "wartortle",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png"
            )
        )
        pokemonList.add(
            Pokemon(
                9,
                "blastoise",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png"
            )
        )
        pokemonList.add(
            Pokemon(
                10,
                "caterpie",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png"
            )
        )
        pokemonList.add(
            Pokemon(
                11,
                "metapod",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png"
            )
        )
        pokemonList.add(
            Pokemon(
                12,
                "butterfree",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png"
            )
        )
        pokemonList.add(
            Pokemon(
                13,
                "weedle",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png"
            )
        )
        pokemonList.add(
            Pokemon(
                14,
                "kakuna",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png"
            )
        )
        pokemonList.add(
            Pokemon(
                15,
                "beedrill",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png"
            )
        )
        pokemonList.add(
            Pokemon(
                16,
                "pidgey",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png"
            )
        )
        pokemonList.add(
            Pokemon(
                17,
                "pidgeotto",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png"
            )
        )
        pokemonList.add(
            Pokemon(
                18,
                "pidgeot",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png"
            )
        )
        pokemonList.add(
            Pokemon(
                19,
                "rattata",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png"
            )
        )
        pokemonList.add(
            Pokemon(
                20,
                "raticate",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png"
            )
        )
        pokemonList.add(
            Pokemon(
                21,
                "spearow",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png"
            )
        )
        pokemonList.add(
            Pokemon(
                22,
                "fearow",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png"
            )
        )
        pokemonList.add(
            Pokemon(
                23,
                "ekans",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png"
            )
        )
        pokemonList.add(
            Pokemon(
                24,
                "arbok",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png"
            )
        )
        pokemonList.add(
            Pokemon(
                25,
                "pikachu",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png"
            )
        )
        pokemonList.add(
            Pokemon(
                26,
                "raichu",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png"
            )
        )
        pokemonList.add(
            Pokemon(
                27,
                "sandshrew",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png"
            )
        )
        pokemonList.add(
            Pokemon(
                28,
                "sandslash",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png"
            )
        )
        pokemonList.add(
            Pokemon(
                29,
                "nidoran-f",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png"
            )
        )
        pokemonList.add(
            Pokemon(
                30,
                "nidorina",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png"
            )
        )
        pokemonList.add(
            Pokemon(
                31,
                "nidoqueen",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png"
            )
        )
        pokemonList.add(
            Pokemon(
                32,
                "nidoran-m",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png"
            )
        )
        pokemonList.add(
            Pokemon(
                33,
                "nidorino",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png"
            )
        )
        pokemonList.add(
            Pokemon(
                34,
                "nidoking",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png"
            )
        )
        pokemonList.add(
            Pokemon(
                35,
                "clefairy",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png"
            )
        )
        pokemonList.add(
            Pokemon(
                36,
                "clefable",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png"
            )
        )
        pokemonList.add(
            Pokemon(
                37,
                "vulpix",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png"
            )
        )
        pokemonList.add(
            Pokemon(
                38,
                "ninetales",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png"
            )
        )
        pokemonList.add(
            Pokemon(
                39,
                "jigglypuff",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png"
            )
        )
        pokemonList.add(
            Pokemon(
                40,
                "wigglytuff",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png"
            )
        )
        pokemonList.add(
            Pokemon(
                41,
                "zubat",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png"
            )
        )
        pokemonList.add(
            Pokemon(
                42,
                "golbat",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png"
            )
        )
        pokemonList.add(
            Pokemon(
                43,
                "oddish",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png"
            )
        )
        pokemonList.add(
            Pokemon(
                44,
                "gloom",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png"
            )
        )
        pokemonList.add(
            Pokemon(
                45,
                "vileplume",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png"
            )
        )
        pokemonList.add(
            Pokemon(
                46,
                "paras",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png"
            )
        )
        pokemonList.add(
            Pokemon(
                47,
                "parasect",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png"
            )
        )
        pokemonList.add(
            Pokemon(
                48,
                "venonat",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png"
            )
        )
        pokemonList.add(
            Pokemon(
                49,
                "venomoth",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png"
            )
        )
        pokemonList.add(
            Pokemon(
                50,
                "diglett",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/50.png"
            )
        )
        pokemonList.add(
            Pokemon(
                51,
                "dugtrio",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/51.png"
            )
        )
        pokemonList.add(
            Pokemon(
                52,
                "meowth",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/52.png"
            )
        )
        pokemonList.add(
            Pokemon(
                53,
                "persian",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/53.png"
            )
        )
        pokemonList.add(
            Pokemon(
                54,
                "psyduck",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/54.png"
            )
        )
        pokemonList.add(
            Pokemon(
                55,
                "golduck",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/55.png"
            )
        )
        pokemonList.add(
            Pokemon(
                56,
                "mankey",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/56.png"
            )
        )
        pokemonList.add(
            Pokemon(
                57,
                "primeape",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/57.png"
            )
        )
        pokemonList.add(
            Pokemon(
                58,
                "growlithe",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/58.png"
            )
        )
        pokemonList.add(
            Pokemon(
                59,
                "arcanine",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/59.png"
            )
        )
        pokemonList.add(
            Pokemon(
                60,
                "poliwag",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/60.png"
            )
        )
        pokemonList.add(
            Pokemon(
                61,
                "poliwhirl",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/61.png"
            )
        )
        pokemonList.add(
            Pokemon(
                62,
                "poliwrath",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/62.png"
            )
        )
        pokemonList.add(
            Pokemon(
                63,
                "abra",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/63.png"
            )
        )
        pokemonList.add(
            Pokemon(
                64,
                "kadabra",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/64.png"
            )
        )
        pokemonList.add(
            Pokemon(
                65,
                "alakazam",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/65.png"
            )
        )
        pokemonList.add(
            Pokemon(
                66,
                "machop",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/66.png"
            )
        )
        pokemonList.add(
            Pokemon(
                67,
                "machoke",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/67.png"
            )
        )
        pokemonList.add(
            Pokemon(
                68,
                "machamp",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/68.png"
            )
        )
        pokemonList.add(
            Pokemon(
                69,
                "bellsprout",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/69.png"
            )
        )
        pokemonList.add(
            Pokemon(
                70,
                "weepinbell",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/70.png"
            )
        )
        pokemonList.add(
            Pokemon(
                71,
                "victreebel",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/71.png"
            )
        )
        pokemonList.add(
            Pokemon(
                72,
                "tentacool",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/72.png"
            )
        )
        pokemonList.add(
            Pokemon(
                73,
                "tentacruel",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/73.png"
            )
        )
        pokemonList.add(
            Pokemon(
                74,
                "geodude",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/74.png"
            )
        )
        pokemonList.add(
            Pokemon(
                75,
                "graveler",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/75.png"
            )
        )
        pokemonList.add(
            Pokemon(
                76,
                "golem",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/76.png"
            )
        )
        pokemonList.add(
            Pokemon(
                77,
                "ponyta",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/77.png"
            )
        )
        pokemonList.add(
            Pokemon(
                78,
                "rapidash",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/78.png"
            )
        )
        pokemonList.add(
            Pokemon(
                79,
                "slowpoke",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/79.png"
            )
        )
        pokemonList.add(
            Pokemon(
                80,
                "slowbro",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/80.png"
            )
        )
        pokemonList.add(
            Pokemon(
                81,
                "magnemite",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/81.png"
            )
        )
        pokemonList.add(
            Pokemon(
                82,
                "magneton",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/82.png"
            )
        )
        pokemonList.add(
            Pokemon(
                83,
                "farfetchd",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/83.png"
            )
        )
        pokemonList.add(
            Pokemon(
                84,
                "doduo",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/84.png"
            )
        )
        pokemonList.add(
            Pokemon(
                85,
                "dodrio",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/85.png"
            )
        )
        pokemonList.add(
            Pokemon(
                86,
                "seel",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/86.png"
            )
        )
        pokemonList.add(
            Pokemon(
                87,
                "dewgong",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/87.png"
            )
        )
        pokemonList.add(
            Pokemon(
                88,
                "grimer",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/88.png"
            )
        )
        pokemonList.add(
            Pokemon(
                89,
                "muk",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/89.png"
            )
        )
        pokemonList.add(
            Pokemon(
                90,
                "shellder",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/90.png"
            )
        )
        pokemonList.add(
            Pokemon(
                91,
                "cloyster",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/91.png"
            )
        )
        pokemonList.add(
            Pokemon(
                92,
                "gastly",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/92.png"
            )
        )
        pokemonList.add(
            Pokemon(
                93,
                "haunter",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/93.png"
            )
        )
        pokemonList.add(
            Pokemon(
                94,
                "gengar",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/94.png"
            )
        )
        pokemonList.add(
            Pokemon(
                95,
                "onix",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/95.png"
            )
        )
        pokemonList.add(
            Pokemon(
                96,
                "drowzee",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/96.png"
            )
        )
        pokemonList.add(
            Pokemon(
                97,
                "hypno",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/97.png"
            )
        )
        pokemonList.add(
            Pokemon(
                98,
                "krabby",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/98.png"
            )
        )
        pokemonList.add(
            Pokemon(
                99,
                "kingler",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/99.png"
            )
        )
        pokemonList.add(
            Pokemon(
                100,
                "voltorb",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/100.png"
            )
        )
        pokemonList.add(
            Pokemon(
                101,
                "electrode",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/101.png"
            )
        )
        pokemonList.add(
            Pokemon(
                102,
                "exeggcute",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/102.png"
            )
        )
        pokemonList.add(
            Pokemon(
                103,
                "exeggutor",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/103.png"
            )
        )
        pokemonList.add(
            Pokemon(
                104,
                "cubone",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/104.png"
            )
        )
        pokemonList.add(
            Pokemon(
                105,
                "marowak",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/105.png"
            )
        )
        pokemonList.add(
            Pokemon(
                106,
                "hitmonlee",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/106.png"
            )
        )
        pokemonList.add(
            Pokemon(
                107,
                "hitmonchan",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/107.png"
            )
        )
        pokemonList.add(
            Pokemon(
                108,
                "lickitung",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/108.png"
            )
        )
        pokemonList.add(
            Pokemon(
                109,
                "koffing",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/109.png"
            )
        )
        pokemonList.add(
            Pokemon(
                110,
                "weezing",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/110.png"
            )
        )
        pokemonList.add(
            Pokemon(
                111,
                "rhyhorn",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/111.png"
            )
        )
        pokemonList.add(
            Pokemon(
                112,
                "rhydon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/112.png"
            )
        )
        pokemonList.add(
            Pokemon(
                113,
                "chansey",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/113.png"
            )
        )
        pokemonList.add(
            Pokemon(
                114,
                "tangela",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/114.png"
            )
        )
        pokemonList.add(
            Pokemon(
                115,
                "kangaskhan",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/115.png"
            )
        )
        pokemonList.add(
            Pokemon(
                116,
                "horsea",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/116.png"
            )
        )
        pokemonList.add(
            Pokemon(
                117,
                "seadra",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/117.png"
            )
        )
        pokemonList.add(
            Pokemon(
                118,
                "goldeen",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/118.png"
            )
        )
        pokemonList.add(
            Pokemon(
                119,
                "seaking",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/119.png"
            )
        )
        pokemonList.add(
            Pokemon(
                120,
                "staryu",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/120.png"
            )
        )
        pokemonList.add(
            Pokemon(
                121,
                "starmie",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/121.png"
            )
        )
        pokemonList.add(
            Pokemon(
                122,
                "mr-mime",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/122.png"
            )
        )
        pokemonList.add(
            Pokemon(
                123,
                "scyther",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/123.png"
            )
        )
        pokemonList.add(
            Pokemon(
                124,
                "jynx",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/124.png"
            )
        )
        pokemonList.add(
            Pokemon(
                125,
                "electabuzz",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/125.png"
            )
        )
        pokemonList.add(
            Pokemon(
                126,
                "magmar",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/126.png"
            )
        )
        pokemonList.add(
            Pokemon(
                127,
                "pinsir",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/127.png"
            )
        )
        pokemonList.add(
            Pokemon(
                128,
                "tauros",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/128.png"
            )
        )
        pokemonList.add(
            Pokemon(
                129,
                "magikarp",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/129.png"
            )
        )
        pokemonList.add(
            Pokemon(
                130,
                "gyarados",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/130.png"
            )
        )
        pokemonList.add(
            Pokemon(
                131,
                "lapras",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/131.png"
            )
        )
        pokemonList.add(
            Pokemon(
                132,
                "ditto",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/132.png"
            )
        )
        pokemonList.add(
            Pokemon(
                133,
                "eevee",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/133.png"
            )
        )
        pokemonList.add(
            Pokemon(
                134,
                "vaporeon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/134.png"
            )
        )
        pokemonList.add(
            Pokemon(
                135,
                "jolteon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/135.png"
            )
        )
        pokemonList.add(
            Pokemon(
                136,
                "flareon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/136.png"
            )
        )
        pokemonList.add(
            Pokemon(
                137,
                "porygon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/137.png"
            )
        )
        pokemonList.add(
            Pokemon(
                138,
                "omanyte",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/138.png"
            )
        )
        pokemonList.add(
            Pokemon(
                139,
                "omastar",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/139.png"
            )
        )
        pokemonList.add(
            Pokemon(
                140,
                "kabuto",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/140.png"
            )
        )
        pokemonList.add(
            Pokemon(
                141,
                "kabutops",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/141.png"
            )
        )
        pokemonList.add(
            Pokemon(
                142,
                "aerodactyl",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/142.png"
            )
        )
        pokemonList.add(
            Pokemon(
                143,
                "snorlax",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/143.png"
            )
        )
        pokemonList.add(
            Pokemon(
                144,
                "articuno",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/144.png"
            )
        )
        pokemonList.add(
            Pokemon(
                145,
                "zapdos",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/145.png"
            )
        )
        pokemonList.add(
            Pokemon(
                146,
                "moltres",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/146.png"
            )
        )
        pokemonList.add(
            Pokemon(
                147,
                "dratini",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/147.png"
            )
        )
        pokemonList.add(
            Pokemon(
                148,
                "dragonair",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/148.png"
            )
        )
        pokemonList.add(
            Pokemon(
                149,
                "dragonite",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/149.png"
            )
        )
        pokemonList.add(
            Pokemon(
                150,
                "mewtwo",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/150.png"
            )
        )
        pokemonList.add(
            Pokemon(
                151,
                "mew",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/151.png"
            )
        )
        pokemonList.add(
            Pokemon(
                152,
                "chikorita",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/152.png"
            )
        )
        pokemonList.add(
            Pokemon(
                153,
                "bayleef",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/153.png"
            )
        )
        pokemonList.add(
            Pokemon(
                154,
                "meganium",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/154.png"
            )
        )
        pokemonList.add(
            Pokemon(
                155,
                "cyndaquil",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/155.png"
            )
        )
        pokemonList.add(
            Pokemon(
                156,
                "quilava",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/156.png"
            )
        )
        pokemonList.add(
            Pokemon(
                157,
                "typhlosion",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/157.png"
            )
        )
        pokemonList.add(
            Pokemon(
                158,
                "totodile",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/158.png"
            )
        )
        pokemonList.add(
            Pokemon(
                159,
                "croconaw",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/159.png"
            )
        )
        pokemonList.add(
            Pokemon(
                160,
                "feraligatr",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/160.png"
            )
        )
        pokemonList.add(
            Pokemon(
                161,
                "sentret",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/161.png"
            )
        )
        pokemonList.add(
            Pokemon(
                162,
                "furret",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/162.png"
            )
        )
        pokemonList.add(
            Pokemon(
                163,
                "hoothoot",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/163.png"
            )
        )
        pokemonList.add(
            Pokemon(
                164,
                "noctowl",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/164.png"
            )
        )
        pokemonList.add(
            Pokemon(
                165,
                "ledyba",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/165.png"
            )
        )
        pokemonList.add(
            Pokemon(
                166,
                "ledian",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/166.png"
            )
        )
        pokemonList.add(
            Pokemon(
                167,
                "spinarak",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/167.png"
            )
        )
        pokemonList.add(
            Pokemon(
                168,
                "ariados",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/168.png"
            )
        )
        pokemonList.add(
            Pokemon(
                169,
                "crobat",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/169.png"
            )
        )
        pokemonList.add(
            Pokemon(
                170,
                "chinchou",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/170.png"
            )
        )
        pokemonList.add(
            Pokemon(
                171,
                "lanturn",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/171.png"
            )
        )
        pokemonList.add(
            Pokemon(
                172,
                "pichu",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/172.png"
            )
        )
        pokemonList.add(
            Pokemon(
                173,
                "cleffa",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/173.png"
            )
        )
        pokemonList.add(
            Pokemon(
                174,
                "igglybuff",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/174.png"
            )
        )
        pokemonList.add(
            Pokemon(
                175,
                "togepi",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/175.png"
            )
        )
        pokemonList.add(
            Pokemon(
                176,
                "togetic",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/176.png"
            )
        )
        pokemonList.add(
            Pokemon(
                177,
                "natu",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/177.png"
            )
        )
        pokemonList.add(
            Pokemon(
                178,
                "xatu",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/178.png"
            )
        )
        pokemonList.add(
            Pokemon(
                179,
                "mareep",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/179.png"
            )
        )
        pokemonList.add(
            Pokemon(
                180,
                "flaaffy",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/180.png"
            )
        )
        pokemonList.add(
            Pokemon(
                181,
                "ampharos",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/181.png"
            )
        )
        pokemonList.add(
            Pokemon(
                182,
                "bellossom",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/182.png"
            )
        )
        pokemonList.add(
            Pokemon(
                183,
                "marill",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/183.png"
            )
        )
        pokemonList.add(
            Pokemon(
                184,
                "azumarill",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/184.png"
            )
        )
        pokemonList.add(
            Pokemon(
                185,
                "sudowoodo",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/185.png"
            )
        )
        pokemonList.add(
            Pokemon(
                186,
                "politoed",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/186.png"
            )
        )
        pokemonList.add(
            Pokemon(
                187,
                "hoppip",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/187.png"
            )
        )
        pokemonList.add(
            Pokemon(
                188,
                "skiploom",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/188.png"
            )
        )
        pokemonList.add(
            Pokemon(
                189,
                "jumpluff",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/189.png"
            )
        )
        pokemonList.add(
            Pokemon(
                190,
                "aipom",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/190.png"
            )
        )
        pokemonList.add(
            Pokemon(
                191,
                "sunkern",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/191.png"
            )
        )
        pokemonList.add(
            Pokemon(
                192,
                "sunflora",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/192.png"
            )
        )
        pokemonList.add(
            Pokemon(
                193,
                "yanma",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/193.png"
            )
        )
        pokemonList.add(
            Pokemon(
                194,
                "wooper",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/194.png"
            )
        )
        pokemonList.add(
            Pokemon(
                195,
                "quagsire",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/195.png"
            )
        )
        pokemonList.add(
            Pokemon(
                196,
                "espeon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/196.png"
            )
        )
        pokemonList.add(
            Pokemon(
                197,
                "umbreon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/197.png"
            )
        )
        pokemonList.add(
            Pokemon(
                198,
                "murkrow",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/198.png"
            )
        )
        pokemonList.add(
            Pokemon(
                199,
                "slowking",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/199.png"
            )
        )
        pokemonList.add(
            Pokemon(
                200,
                "misdreavus",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/200.png"
            )
        )
        pokemonList.add(
            Pokemon(
                201,
                "unown",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/201.png"
            )
        )
        pokemonList.add(
            Pokemon(
                202,
                "wobbuffet",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/202.png"
            )
        )
        pokemonList.add(
            Pokemon(
                203,
                "girafarig",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/203.png"
            )
        )
        pokemonList.add(
            Pokemon(
                204,
                "pineco",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/204.png"
            )
        )
        pokemonList.add(
            Pokemon(
                205,
                "forretress",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/205.png"
            )
        )
        pokemonList.add(
            Pokemon(
                206,
                "dunsparce",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/206.png"
            )
        )
        pokemonList.add(
            Pokemon(
                207,
                "gligar",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/207.png"
            )
        )
        pokemonList.add(
            Pokemon(
                208,
                "steelix",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/208.png"
            )
        )
        pokemonList.add(
            Pokemon(
                209,
                "snubbull",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/209.png"
            )
        )
        pokemonList.add(
            Pokemon(
                210,
                "granbull",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/210.png"
            )
        )
        pokemonList.add(
            Pokemon(
                211,
                "qwilfish",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/211.png"
            )
        )
        pokemonList.add(
            Pokemon(
                212,
                "scizor",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/212.png"
            )
        )
        pokemonList.add(
            Pokemon(
                213,
                "shuckle",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/213.png"
            )
        )
        pokemonList.add(
            Pokemon(
                214,
                "heracross",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/214.png"
            )
        )
        pokemonList.add(
            Pokemon(
                215,
                "sneasel",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/215.png"
            )
        )
        pokemonList.add(
            Pokemon(
                216,
                "teddiursa",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/216.png"
            )
        )
        pokemonList.add(
            Pokemon(
                217,
                "ursaring",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/217.png"
            )
        )
        pokemonList.add(
            Pokemon(
                218,
                "slugma",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/218.png"
            )
        )
        pokemonList.add(
            Pokemon(
                219,
                "magcargo",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/219.png"
            )
        )
        pokemonList.add(
            Pokemon(
                220,
                "swinub",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/220.png"
            )
        )
        pokemonList.add(
            Pokemon(
                221,
                "piloswine",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/221.png"
            )
        )
        pokemonList.add(
            Pokemon(
                222,
                "corsola",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/222.png"
            )
        )
        pokemonList.add(
            Pokemon(
                223,
                "remoraid",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/223.png"
            )
        )
        pokemonList.add(
            Pokemon(
                224,
                "octillery",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/224.png"
            )
        )
        pokemonList.add(
            Pokemon(
                225,
                "delibird",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/225.png"
            )
        )
        pokemonList.add(
            Pokemon(
                226,
                "mantine",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/226.png"
            )
        )
        pokemonList.add(
            Pokemon(
                227,
                "skarmory",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/227.png"
            )
        )
        pokemonList.add(
            Pokemon(
                228,
                "houndour",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/228.png"
            )
        )
        pokemonList.add(
            Pokemon(
                229,
                "houndoom",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/229.png"
            )
        )
        pokemonList.add(
            Pokemon(
                230,
                "kingdra",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/230.png"
            )
        )
        pokemonList.add(
            Pokemon(
                231,
                "phanpy",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/231.png"
            )
        )
        pokemonList.add(
            Pokemon(
                232,
                "donphan",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/232.png"
            )
        )
        pokemonList.add(
            Pokemon(
                233,
                "porygon2",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/233.png"
            )
        )
        pokemonList.add(
            Pokemon(
                234,
                "stantler",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/234.png"
            )
        )
        pokemonList.add(
            Pokemon(
                235,
                "smeargle",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/235.png"
            )
        )
        pokemonList.add(
            Pokemon(
                236,
                "tyrogue",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/236.png"
            )
        )
        pokemonList.add(
            Pokemon(
                237,
                "hitmontop",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/237.png"
            )
        )
        pokemonList.add(
            Pokemon(
                238,
                "smoochum",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/238.png"
            )
        )
        pokemonList.add(
            Pokemon(
                239,
                "elekid",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/239.png"
            )
        )
        pokemonList.add(
            Pokemon(
                240,
                "magby",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/240.png"
            )
        )
        pokemonList.add(
            Pokemon(
                241,
                "miltank",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/241.png"
            )
        )
        pokemonList.add(
            Pokemon(
                242,
                "blissey",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/242.png"
            )
        )
        pokemonList.add(
            Pokemon(
                243,
                "raikou",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/243.png"
            )
        )
        pokemonList.add(
            Pokemon(
                244,
                "entei",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/244.png"
            )
        )
        pokemonList.add(
            Pokemon(
                245,
                "suicune",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/245.png"
            )
        )
        pokemonList.add(
            Pokemon(
                246,
                "larvitar",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/246.png"
            )
        )
        pokemonList.add(
            Pokemon(
                247,
                "pupitar",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/247.png"
            )
        )
        pokemonList.add(
            Pokemon(
                248,
                "tyranitar",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/248.png"
            )
        )
        pokemonList.add(
            Pokemon(
                249,
                "lugia",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/249.png"
            )
        )
        pokemonList.add(
            Pokemon(
                250,
                "ho-oh",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/250.png"
            )
        )
        pokemonList.add(
            Pokemon(
                251,
                "celebi",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/251.png"
            )
        )
        pokemonList.add(
            Pokemon(
                252,
                "treecko",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/252.png"
            )
        )
        pokemonList.add(
            Pokemon(
                253,
                "grovyle",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/253.png"
            )
        )
        pokemonList.add(
            Pokemon(
                254,
                "sceptile",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/254.png"
            )
        )
        pokemonList.add(
            Pokemon(
                255,
                "torchic",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/255.png"
            )
        )
        pokemonList.add(
            Pokemon(
                256,
                "combusken",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/256.png"
            )
        )
        pokemonList.add(
            Pokemon(
                257,
                "blaziken",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/257.png"
            )
        )
        pokemonList.add(
            Pokemon(
                258,
                "mudkip",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/258.png"
            )
        )
        pokemonList.add(
            Pokemon(
                259,
                "marshtomp",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/259.png"
            )
        )
        pokemonList.add(
            Pokemon(
                260,
                "swampert",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/260.png"
            )
        )
        pokemonList.add(
            Pokemon(
                261,
                "poochyena",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/261.png"
            )
        )
        pokemonList.add(
            Pokemon(
                262,
                "mightyena",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/262.png"
            )
        )
        pokemonList.add(
            Pokemon(
                263,
                "zigzagoon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/263.png"
            )
        )
        pokemonList.add(
            Pokemon(
                264,
                "linoone",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/264.png"
            )
        )
        pokemonList.add(
            Pokemon(
                265,
                "wurmple",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/265.png"
            )
        )
        pokemonList.add(
            Pokemon(
                266,
                "silcoon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/266.png"
            )
        )
        pokemonList.add(
            Pokemon(
                267,
                "beautifly",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/267.png"
            )
        )
        pokemonList.add(
            Pokemon(
                268,
                "cascoon",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/268.png"
            )
        )
        pokemonList.add(
            Pokemon(
                269,
                "dustox",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/269.png"
            )
        )
        pokemonList.add(
            Pokemon(
                270,
                "lotad",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/270.png"
            )
        )
        pokemonList.add(
            Pokemon(
                271,
                "lombre",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/271.png"
            )
        )
        pokemonList.add(
            Pokemon(
                272,
                "ludicolo",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/272.png"
            )
        )
        pokemonList.add(
            Pokemon(
                273,
                "seedot",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/273.png"
            )
        )
        pokemonList.add(
            Pokemon(
                274,
                "nuzleaf",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/274.png"
            )
        )
        pokemonList.add(
            Pokemon(
                275,
                "shiftry",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/275.png"
            )
        )
        pokemonList.add(
            Pokemon(
                276,
                "taillow",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/276.png"
            )
        )
        pokemonList.add(
            Pokemon(
                277,
                "swellow",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/277.png"
            )
        )
        pokemonList.add(
            Pokemon(
                278,
                "wingull",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/278.png"
            )
        )
        pokemonList.add(
            Pokemon(
                279,
                "pelipper",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/279.png"
            )
        )
        pokemonList.add(
            Pokemon(
                280,
                "ralts",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/280.png"
            )
        )
        pokemonList.add(
            Pokemon(
                281,
                "kirlia",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/281.png"
            )
        )
        pokemonList.add(
            Pokemon(
                282,
                "gardevoir",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/282.png"
            )
        )
        pokemonList.add(
            Pokemon(
                283,
                "surskit",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/283.png"
            )
        )
        pokemonList.add(
            Pokemon(
                284,
                "masquerain",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/284.png"
            )
        )
        pokemonList.add(
            Pokemon(
                285,
                "shroomish",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/285.png"
            )
        )
        pokemonList.add(
            Pokemon(
                286,
                "breloom",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/286.png"
            )
        )
        pokemonList.add(
            Pokemon(
                287,
                "slakoth",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/287.png"
            )
        )
        pokemonList.add(
            Pokemon(
                288,
                "vigoroth",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/288.png"
            )
        )
        pokemonList.add(
            Pokemon(
                289,
                "slaking",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/289.png"
            )
        )
        pokemonList.add(
            Pokemon(
                290,
                "nincada",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/290.png"
            )
        )
        pokemonList.add(
            Pokemon(
                291,
                "ninjask",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/291.png"
            )
        )
        pokemonList.add(
            Pokemon(
                292,
                "shedinja",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/292.png"
            )
        )
        pokemonList.add(
            Pokemon(
                293,
                "whismur",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/293.png"
            )
        )
        pokemonList.add(
            Pokemon(
                294,
                "loudred",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/294.png"
            )
        )
        pokemonList.add(
            Pokemon(
                295,
                "exploud",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/295.png"
            )
        )
        pokemonList.add(
            Pokemon(
                296,
                "makuhita",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/296.png"
            )
        )
        pokemonList.add(
            Pokemon(
                297,
                "hariyama",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/297.png"
            )
        )
        pokemonList.add(
            Pokemon(
                298,
                "azurill",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/298.png"
            )
        )
        pokemonList.add(
            Pokemon(
                299,
                "nosepass",
                "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/299.png"
            )
        )
    }
}